// Here's how we would access our contract:
var abi = /* abi generated by the compiler */
var CardGeneratorContract = web3.eth.contract(abi)
var contractAddress = /* our contract address on Ethereum after deploying */
var CardGenerator = CardGeneratorContract.at(contractAddress)
// `CardGenerator` has access to our contract's public functions and events

// some sort of event listener to take the text input:
$("#ourButton").click(function(e) {
  var name = $("#nameInput").val()
  // Call our contract's `createRandomCard` function:
  CardGenerator.createRandomCard(name)
})

// Listen for the `NewCard` event, and update the UI
var event = CardGenerator.NewCard(function(error, result) {
  if (error) return
  generateCard(result.cardId, result.name, result.dna)
})

// take the Card dna, and update our image
function generateCard(id, name, dna) {
  let dnaStr = String(dna)
  // pad DNA with leading zeroes if it's less than 16 characters
  while (dnaStr.length < 16)
    dnaStr = "0" + dnaStr

  let cardDetails = {
    // first 2 digits make up the head. We have 7 possible heads, so % 7
    // to get a number 0 - 6, then add 1 to make it 1 - 7. Then we have 7
    // image files named "head1.png" through "head7.png" we load based on
    // this number:
    headChoice: dnaStr.substring(0, 2) % 7 + 1,
    // 2nd 2 digits make up the eyes, 11 variations:
    eyeChoice: dnaStr.substring(2, 4) % 11 + 1,
    // 6 variations of shirts:
    shirtChoice: dnaStr.substring(4, 6) % 6 + 1,
    // last 6 digits control color. Updated using CSS filter: hue-rotate
    // which has 360 degrees:
    skinColorChoice: parseInt(dnaStr.substring(6, 8) / 100 * 360),
    eyeColorChoice: parseInt(dnaStr.substring(8, 10) / 100 * 360),
    clothesColorChoice: parseInt(dnaStr.substring(10, 12) / 100 * 360),
    cardName: name,
    cardDescription: "A Level 1 CryptoCard",
  }
  return cardDetails
}